let fullName = "Nafisa Tabassum Sraboni";
let age=22;
let country="Bangladesh";
let favouriteLanguage = "JavaScript";
let dreamJob = "Full-Stack Developer";
let yearsToGoal = 1;
let isLearningJS = true;

console.log("----------------------------------------");
console.log("----------------------------------------");
console.log("                                        ");
console.log("Name: "+fullName);
console.log("Age: "+age);
console.log("Country: "+country);
console.log("Favourite Language: "+favouriteLanguage);
console.log("Dream Job: "+dreamJob);
console.log("Years to Reach Goal: "+yearsToGoal);
console.log("Learning JavaScript: "+yearsToGoal);
console.log("                                        ");
console.log("----------------------------------------");
console.log("----------------------------------------");
